---
title: "Análise de GPD per capita -Dash"
output: 
  flexdashboard::flex_dashboard:
    runtime: shiny
    theme:
      bg: "#E0E0E0"
      fg: "#101010" 
      primary: "#101010"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(summarytools)
library(knitr)
library(rmarkdown)
library(kableExtra)
library(ggplot2)
library(stargazer)
library(shiny)
library(mice)
```

```{r mudando o diretorio, echo=FALSE}
setwd("/Users/hpasi/OneDrive/Área de Trabalho/ANÁLISE EXPL. DE DADOS/Projeto final")

df <- readxl::read_excel(file.choose(setwd))

df_gdp <-df[df$country %in% c("Brazil", "Cuba", "Japan", "Italy"), ]


data_pop_subset <- subset(df_gdp, is.na(df_gdp$log_pop))
data_gdp_subset <- subset(df_gdp, is.na(df_gdp$log_gdppc))
data_educ_subset <- subset(df_gdp, is.na(df_gdp$educ))

imputed_data <- mice(df_gdp, m=5, method = "rf")

finished_imputed_data <- complete(imputed_data, mean(1:5))
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------


## UI

```{r}
ui <- fluidPage(
  
  # Título do dashboard
  titlePanel("Variação do PIB (GDP)"),
  
  # Sidebar com os controles do usuário
  sidebarLayout(
    sidebarPanel(
      
      # Seleciona o país
      selectInput("country", "País:", 
                  choices = c("Brazil", "Cuba", "Japan", "Italy"),
                  selected = "Brazil"),
      
      # Seleciona a cor da linha
      radioButtons("color", "Cor da linha:",
                   choices = c("Azul" = "blue", "Vermelho" = "red", "Verde" = "green"),
                   selected = "Azul"),
      
      # Definindo o intervalo do eixo x (year)
      sliderInput("x_range", "Intervalo do eixo x (anos):", 
                  min = 1960, max = 2000, value = c(1960, 2000),
                  step = 5),
      
      # Definindo o intervalo do eixo y (GDP)
      sliderInput("y_range", "Intervalo do eixo y (GDP):", 
                  min = 0, max = 12, value = c(0, 12),
                  step = 2)
      
    ),
    
    # Renderiza o gráfico de linha
    mainPanel(
      plotOutput("gdp_plot")
    )
  )
)
```


## SERVER
```{r}
server <- function(input, output) {

  # Filtra os dados com base no país selecionado
  filtered_data <- reactive({
    finished_imputed_data %>%
      filter(country == input$country)
  })
  
  
  # Renderiza o gráfico de linha
  output$gdp_plot <- renderPlot({
    ggplot(filtered_data(), aes(x = year, y = log_gdppc, color = input$color)) +
      geom_line() + 
      scale_x_continuous(limits = c(input$x_range[1], input$x_range[2])) +
      scale_y_continuous(limits = c(input$y_range[1], input$y_range[2])) +
      labs(title = paste("Variação do GDP de", input$country), x = "Ano", y = "GDP")
  })
  
}
```


```{r}
shinyApp(ui, server)
```


